### ISSUE TITLE
Alternative plugin/module for Wordpress?

### ISSUE THREAD

**Issue by Cu8eR** [megasnort/fork-cms-module-elo-rating#36]
I am sorry for this issue which is not related to your module. However, dont you wanna create this plugin for Wordpress too? I have big difficulties with maintaining my Fork CMS due to complicated updates between major versions :( If not, do you know any alternative? Thank you very much!

**Comment by megasnort** [comment]
No, I will not do that :)
Not really fan of developing for Wordpress.

**Comment by Cu8eR** [comment]
Please, can you recommend me any guide how to easily update form cms from 3.8.x to 3.9.x release without loosing my data? Thank you very much

**Comment by megasnort** [comment]
Is there a specific reason why you want to update to Fork 3.9? The newer version of the elo-rating module does not offer any new features. I refactored the code a bit and added the Czech translation. Nothing else.

**Comment by Cu8eR** [comment]
I am afraid that I will need to update once in future to newer fork cms... I dont wanna lose my content :( I dont know why they dont offer easy updater just like wordpress or other cms system

**Comment by megasnort** [comment]
Wordpress is a CMS backed by a big company ([Automattic](https://automattic.com/about/) - 429 employees) used by thousands of companies. The same goes for Drupal.

Fork CMS is CMS used by let us say a few companies and users and is not really backed by one company. It's mainly volunteers improving Fork, doing it for fun.

Focus with smaller CMS's will because of that always be

1. New features and Bugfixing
...
10. Backwards compatibility

That said. I would first check if there are actually new features in Fork 3.9 that you want to use. Probably not. Most of the work now goes into the integration of [Symfony](https://symfony.com/). It improves the code base a lot, but does not offer any new features for the users. My suggestion: Don't upgrade a Fork website when you've got it running. It has never been worth the effort (I have never updated a Fork website)

Also, the next release of Fork (probably 4.0) will totally break backwards compatibility because a massive amount of Symfony integrations, implementation of Bootstrap in the backend and probably implementation of Twig in the Frontend.
